### ISSUE TITLE
TEST FAILURE: Round

### ISSUE THREAD

**Issue by cen19** [Rawnly/js-challenges#4]
- [x] This is a problem with a test 
- [ ] This is an idea for a new challenge

#### Challenge code:
```js
```

----
### The issue:
The tests for the round problem seems wrong.

**Comment by rawnly** [comment]
Can you show me your function? The tests are based on the `solutions.js` file. The `round` function should round a number to 0 decimal places (maybe i should update it to 1 or 2) and tests it with `PI`.

**Comment by rawnly** [comment]
Below the code from `solutions.js`. This one pass the test.

```js
/**
 * CHALLENGE 1: ROUND NUMBER
 * @name round
 * @description Write a function that round a number (`n`) to given decimal places.
 * @author Federico Vitale <fedevitale99[at]gmail.com>
 *
 * 
 * @example Usage:
 * round(Math.PI, 2) // => 3.14
 * 
 * 
 * @param {Number} n The number to be rounded
 * @param {Number} places Decimal places
 * 
 * @returns {Number} Rounded number
 */

module.exports.round = function (n, places = 0) {
	places = Math.pow(10, places)

	return Math.floor(n * places) / places;
}
```

**Comment by cen19** [comment]
Yes that solution looks to work. I'm not sure if the /tests/ are the tests being used but in the version I have, the test for round is

```
test('ROUND', t => {
	var argument = 'hello';
	var output = round(argument);

	return t.deepEqual(output, solutions.round(argument));
})
```

Is the argument supposed to be 'hello'?

**Comment by rawnly** [comment]
Oh sorry, I forgot it, please change the argument to Math.PI
